name: Android Pull Request CI

on:
  pull_request:
    branches: 'develop'

jobs:
  create-dependencies:
    name: Create API key file
    runs-on: ubuntu-18.04
    steps:
      - name: Create API key file
        shell: bash
        run: |
          echo "apiKey=0" >> api.properties
          cat api.properties
      - name: Upload API key file
        uses: actions/upload-artifact@v1
        with:
          name: api.properties

  code-analysis:
    name: Run Detekt for static code analysis
    needs: create-dependencies
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download API key file
        uses: actions/download-artifact@v1
        with:
          name: api.properties
      - name: Run Detekt
        run: |
          cat api.properties
          bash ./gradlew detekt

  test:
    name: Runs all module unit tests and check test coverage
    needs: create-dependencies
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download API key file
        uses: actions/download-artifact@v1
        with:
          name: api.properties
      - name: Generate Jacoco test report
        run: bash ./gradlew jacocoTestReport
      - name: Check code coverage
        run: |
          cat api.properties
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f build/reports/jacoco/jacocoTestReport.xml

